# Copyright (c) 2025 Shubham Panchal (Joey). MIT License.
import html
import json
from typing import Dict, List, Set, Optional
import networkx as nx

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Impact Report</title>
<script src="https://d3js.org/d3.v7.min.js"></script>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0d1117; color: #c9d1d9; padding: 20px; }}
  h1 {{ color: #58a6ff; margin-bottom: 8px; }}
  .meta {{ color: #8b949e; font-size: 14px; margin-bottom: 24px; }}
  .summary {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); gap: 12px; margin-bottom: 24px; }}
  .stat {{ background: #161b22; border: 1px solid #30363d; border-radius: 6px; padding: 16px; text-align: center; }}
  .stat .value {{ font-size: 28px; font-weight: 600; color: #f0f6fc; }}
  .stat .label {{ font-size: 12px; color: #8b949e; margin-top: 4px; }}
  .stat .value.danger {{ color: #f85149; }}
  .stat .value.warning {{ color: #d29922; }}
  .stat .value.ok {{ color: #3fb950; }}
  #graph {{ border: 1px solid #30363d; border-radius: 6px; background: #0d1117; margin-bottom: 24px; }}
  .controls {{ margin-bottom: 12px; }}
  .controls button {{ background: #21262d; border: 1px solid #30363d; color: #c9d1d9; padding: 6px 14px; border-radius: 6px; cursor: pointer; margin-right: 6px; font-size: 13px; }}
  .controls button:hover {{ background: #30363d; }}
  .legend {{ display: flex; gap: 16px; margin-bottom: 12px; font-size: 13px; }}
  .legend-item {{ display: flex; align-items: center; gap: 6px; }}
  .legend-dot {{ width: 12px; height: 12px; border-radius: 50%; }}
  table {{ width: 100%; border-collapse: collapse; }}
  th, td {{ padding: 8px 12px; text-align: left; border-bottom: 1px solid #21262d; font-size: 13px; }}
  th {{ color: #8b949e; font-weight: 600; }}
  td {{ color: #c9d1d9; }}
  .hotspot-list {{ margin-top: 24px; }}
  .footer {{ color: #8b949e; font-size: 12px; margin-top: 24px; text-align: center; }}
</style>
</head>
<body>
<h1>Impact Report</h1>
<div class="meta">Generated by impact-engine v{version} &mdash; {project} &mdash; {date}</div>
<div class="summary">
  <div class="stat"><div class="value">{nodes}</div><div class="label">Functions</div></div>
  <div class="stat"><div class="value">{edges}</div><div class="label">Dependencies</div></div>
  <div class="stat"><div class="value {changed_class}">{changed}</div><div class="label">Changed</div></div>
  <div class="stat"><div class="value {dead_class}">{dead}</div><div class="label">Dead Code</div></div>
  <div class="stat"><div class="value {risk_class}">{max_risk}</div><div class="label">Max Risk</div></div>
  <div class="stat"><div class="value">{cycles}</div><div class="label">Cycles</div></div>
</div>
<div class="legend">
  <div class="legend-item"><div class="legend-dot" style="background:#3fb950"></div> Low risk</div>
  <div class="legend-item"><div class="legend-dot" style="background:#d29922"></div> Medium risk</div>
  <div class="legend-item"><div class="legend-dot" style="background:#f85149"></div> High risk</div>
  <div class="legend-item"><div class="legend-dot" style="background:#bc8cff"></div> Changed</div>
</div>
<div class="controls">
  <button onclick="zoomIn()">+ Zoom</button>
  <button onclick="zoomOut()">- Zoom</button>
  <button onclick="resetView()">Reset</button>
  <button onclick="toggleLabels()">Toggle Labels</button>
</div>
<div id="graph"></div>
<script>
const data = {graph_data};
const width = document.getElementById('graph').clientWidth || 900;
const height = Math.max(600, data.nodes.length * 6);

const svg = d3.select('#graph').append('svg')
    .attr('width', width).attr('height', height);

const g = svg.append('g');

const zoom = d3.zoom().scaleExtent([0.1, 4]).on('zoom', (e) => g.attr('transform', e.transform));
svg.call(zoom);

function zoomIn() {{ svg.transition().call(zoom.scaleBy, 1.3); }}
function zoomOut() {{ svg.transition().call(zoom.scaleBy, 0.7); }}
function resetView() {{ svg.transition().call(zoom.transform, d3.zoomIdentity); }}

let showLabels = true;
function toggleLabels() {{
  showLabels = !showLabels;
  g.selectAll('.node-label').attr('display', showLabels ? 'block' : 'none');
}}

const color = d3.scaleOrdinal(d3.schemeSet2);

const simulation = d3.forceSimulation(data.nodes)
    .force('link', d3.forceLink(data.links).id(d => d.id).distance(80))
    .force('charge', d3.forceManyBody().strength(-200))
    .force('center', d3.forceCenter(width / 2, height / 2))
    .force('collision', d3.forceCollide(20));

const link = g.append('g').selectAll('line')
    .data(data.links).join('line')
    .attr('stroke', '#30363d').attr('stroke-width', 1.5).attr('stroke-opacity', 0.6);

const node = g.append('g').selectAll('circle')
    .data(data.nodes).join('circle')
    .attr('r', d => Math.max(5, Math.min(12, d.risk + 2)))
    .attr('fill', d => d.changed ? '#bc8cff' : d.risk >= 5 ? '#f85149' : d.risk >= 2 ? '#d29922' : '#3fb950')
    .attr('stroke', d => d.changed ? '#bc8cff' : '#30363d')
    .attr('stroke-width', d => d.changed ? 3 : 1.5)
    .attr('cursor', 'pointer')
    .append('title').text(d => d.id);

const label = g.append('g').selectAll('text')
    .data(data.nodes).join('text')
    .attr('class', 'node-label')
    .attr('dx', 14).attr('dy', 4)
    .attr('font-size', '10px')
    .attr('fill', '#c9d1d9')
    .text(d => d.label);

simulation.on('tick', () => {{
  link.attr('x1', d => d.source.x).attr('y1', d => d.source.y)
      .attr('x2', d => d.target.x).attr('y2', d => d.target.y);
  node.attr('cx', d => d.x).attr('cy', d => d.y);
  label.attr('x', d => d.x).attr('y', d => d.y);
}});
</script>
<div class="hotspot-list">
<h2>Top Risk Hotspots</h2>
<table>
<tr><th>Function</th><th>Risk</th><th>Outgoing</th><th>Incoming</th><th>Changed</th></tr>
{hotspot_rows}
</table>
</div>
<div class="footer">impact-engine v{version} &mdash; MIT License</div>
</body>
</html>"""


def export_html(
    graph: nx.DiGraph,
    project: str = "",
    version: str = "0.4.0",
    changed_nodes: Optional[Set[str]] = None,
    dead_nodes: Optional[List[str]] = None,
    cycles: Optional[List[List[str]]] = None,
    max_risk: int = 0,
) -> str:
    from datetime import datetime

    changed_set = set(changed_nodes or [])
    dead_list = list(dead_nodes or [])
    cycles_list = list(cycles or [])

    nodes_data = []
    for n in graph.nodes():
        risk = graph.out_degree(n)
        nodes_data.append({
            "id": n,
            "label": n.split("::")[-1],
            "risk": risk,
            "changed": n in changed_set,
        })

    links_data = []
    for u, v in graph.edges():
        links_data.append({"source": u, "target": v})

    hotspot_rows = "".join(
        f"<tr><td>{html.escape(str(n['id']))}</td><td>{n['risk']}</td>"
        f"<td>{graph.out_degree(n['id'])}</td><td>{graph.in_degree(n['id'])}</td>"
        f"<td>{'<span style=\"color:#bc8cff\">yes</span>' if n['changed'] else 'no'}</td></tr>"
        for n in sorted(nodes_data, key=lambda x: -x['risk'])[:50]
    )

    changed_count = len(changed_set)
    dead_count = len(dead_list)

    changed_class = "danger" if changed_count > 0 else "ok"
    dead_class = "warning" if dead_count > 0 else "ok"
    risk_class = "danger" if max_risk >= 5 else ("warning" if max_risk >= 2 else "ok")

    return HTML_TEMPLATE.format(
        version=version,
        project=project,
        date=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        nodes=graph.number_of_nodes(),
        edges=graph.number_of_edges(),
        changed=changed_count,
        dead=dead_count,
        cycles=len(cycles_list),
        max_risk=max_risk,
        changed_class=changed_class,
        dead_class=dead_class,
        risk_class=risk_class,
        graph_data=json.dumps({"nodes": nodes_data, "links": links_data}),
        hotspot_rows=hotspot_rows,
    )
